### ISSUE TITLE
[Question] 使用唐可可报风控

### ISSUE THREAD

**Issue by KafCoppelia** [kosakarin/hoshino_big_cockroach#2]
使用“唐可可 简单”，报错如下：
01-09 09:07:30 [ERROR] nonebot | Running matcher <Matcher from random_tkk, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/nonebot_v2/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/root/NONEBOT/AQUABOT/src/plugins/random_tkk/__init__.py", line 154, in random_tkk
    await bot.send(event, msg)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 471, in send
    return await self.send_msg(**params)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 172, in call_api
    raise exception
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 363, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 192, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 153}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
CQHTTP那边报风控：
`[2022-01-09 09:07:30] [WARNING]: 群消息发送失败: 账号可能被风控.`

**Comment by kosakarin** [comment]
none2吗，none2我没适配，我也不知道会出什么问题，而且CQ返回的话凡是发送失败都会报风控，也没法具体区分是什么原因，你这个是偶尔发生还是经常发生啊

**Comment by KafCoppelia** [comment]
一直发生

**Comment by kosakarin** [comment]
我看你这个是改的none2的代码，none2那边我确实不太清楚，尝试把event换成ctx？

**Comment by KafCoppelia** [comment]
好的，我尝试修改源码试试，问题先close，后续再问
